import { getAuthenticatedUser } from "@/lib/auth/session";
import { propertyOwner, propertyPatchSchema } from "@/lib/partner/service";
import { FieldValue, GeoPoint } from "firebase-admin/firestore";
import { adminDb } from "@/lib/firebase/admin";

export async function GET(_: Request, { params }: RouteContext<"/api/partner/properties/[propertyId]">) {
  const user = await getAuthenticatedUser(); if (!user) return Response.json({ error: "Unauthenticated." }, { status: 401 });
  try { const { propertyId } = await params; const ref = await propertyOwner(user.uid, propertyId); const [property, rooms, rates, policies, media, documents] = await Promise.all([ref.get(), adminDb.collection("roomTypes").where("propertyId", "==", propertyId).limit(50).get(), adminDb.collection("ratePlans").where("propertyId", "==", propertyId).limit(100).get(), adminDb.collection("cancellationPolicies").where("propertyId", "==", propertyId).get(), adminDb.collection("mediaAssets").where("propertyId", "==", propertyId).get(), adminDb.collection("verificationDocuments").where("propertyId", "==", propertyId).get()]); const p = property.data() ?? {}; return Response.json({ property: { id: property.id, name: p.name, propertyType: p.propertyType, description: p.description, address: p.address, latitude: p.geoPoint?.latitude, longitude: p.geoPoint?.longitude, googlePlaceId: p.googlePlaceId, timezone: p.timezone, checkInTime: p.checkInTime, checkOutTime: p.checkOutTime, publicPhone: p.publicPhone, publicEmail: p.publicEmail, floors: p.floors ?? 0, totalPhysicalRooms: p.totalPhysicalRooms, otaUrls: p.otaUrls ?? [], amenityIds: p.amenityIds ?? [], roomAmenityIds: p.roomAmenityIds ?? [], childrenPolicy: p.childrenPolicy ?? {}, petPolicy: p.petPolicy ?? {}, smokingPolicy: p.smokingPolicy ?? {}, identityRequirements: p.identityRequirements ?? {}, coverMediaId: p.coverMediaId, cancellationPolicyIds: p.cancellationPolicyIds ?? [], onboarding: p.onboarding ?? { currentStep: 1, completedSteps: [] }, status: p.status, approvalStatus: p.approvalStatus, rejectionReason: p.rejectionReason }, roomTypes: rooms.docs.map((doc) => ({ id: doc.id, name: doc.data().name, description: doc.data().description, inventory: doc.data().totalInventory, maxAdults: doc.data().maxAdults, amenityIds: doc.data().amenityIds ?? [] })), ratePlans: rates.docs.map((doc) => ({ id: doc.id, name: doc.data().name, code: doc.data().code, basePricePaise: doc.data().basePricePaise, roomTypeId: doc.data().roomTypeId, cancellationPolicyId: doc.data().cancellationPolicyId })), policies: policies.docs.map(d => ({ id: d.id, ...d.data() })), media: media.docs.map(d => ({ id: d.id, ...d.data() })), documents: documents.docs.map(d => ({ id: d.id, ...d.data() })) }); }
  catch { return Response.json({ error: "Property access required." }, { status: 403 }); }
}

export async function PATCH(request: Request, { params }: RouteContext<"/api/partner/properties/[propertyId]">) {
  const user = await getAuthenticatedUser(); if (!user) return Response.json({ error: "Unauthenticated." }, { status: 401 });
  try { const { propertyId } = await params; const ref = await propertyOwner(user.uid, propertyId); const patch = propertyPatchSchema.parse(await request.json()); const location = patch.latitude !== undefined || patch.longitude !== undefined || patch.address || patch.googlePlaceId || patch.timezone; if (location && (patch.latitude === undefined || patch.longitude === undefined || !patch.address || !patch.googlePlaceId || !patch.timezone)) throw new Error("COMPLETE_PLACE_REQUIRED"); if (patch.timezone) { try { Intl.DateTimeFormat(undefined, { timeZone: patch.timezone }); } catch { throw new Error("INVALID_TIMEZONE"); } } const update: Record<string, unknown> = { ...patch, updatedAt: FieldValue.serverTimestamp(), updatedBy: user.uid }; if (patch.latitude !== undefined && patch.longitude !== undefined) { update.geoPoint = new GeoPoint(patch.latitude, patch.longitude); update.geohash = `${patch.latitude.toFixed(4)}:${patch.longitude.toFixed(4)}`; delete update.latitude; delete update.longitude; } await ref.update(update); return Response.json({ ok: true }); }
  catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Unable to save property." }, { status: 422 }); }
}
