export const queryKeys = {
  auth: ["auth"] as const,
  home: ["catalog", "home"] as const,
  search: (filters: Record<string, unknown>) => ["catalog", "search", filters] as const,
  property: (slug: string) => ["catalog", "property", slug] as const,
  bookable: (slug: string, stay: Record<string, unknown>) => ["catalog", "bookable", slug, stay] as const,
  notifications: (unreadOnly = false) => ["notifications", { unreadOnly }] as const,
  partnerShell: ["partner", "shell"] as const,
  partnerOverview: (propertyId: string) => ["partner", propertyId, "overview"] as const,
  partnerRooms: (propertyId: string) => ["partner", propertyId, "rooms"] as const,
  partnerReservations: (propertyId: string, filters: Record<string, unknown>) => ["partner", propertyId, "reservations", filters] as const,
  partnerListing: (propertyId: string, section?: string) => ["partner", propertyId, "listing", section ?? "all"] as const,
  partnerReviews: (propertyId: string) => ["partner", propertyId, "reviews"] as const,
  bookings: ["customer", "bookings"] as const,
} as const;
