"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Bath, BedDouble, BriefcaseBusiness, Check, ChevronDown, ChevronRight, Coffee, Dumbbell, Heart, Hotel, MapPin, Share2, ShieldCheck, Star, Utensils, Users, Wifi } from "lucide-react";
import { SiteHeader } from "@/components/home/home-page";
import { LoginModal } from "@/components/auth/login-modal";

type Property = { slug: string; name: string; city: string; state: string | null; propertyType: string; ratingAverage: number; ratingCount: number; minimumPricePaise: number | null; currency: string; coverImageUrl: string | null; amenityCodes: string[]; freeCancellation: boolean };
const money = (value: number | null, currency: string) => value === null ? "Price on request" : new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(value / 100);
const defaults = ["Fast Wi-Fi", "Business Centre", "Fine Dining", "Fitness Centre", "Breakfast Available", "Laundry Service"];

export function LiveHotelDetail({ slug }: { slug: string }) {
  const [property, setProperty] = useState<Property | null>(null); const [error, setError] = useState(""); const [saved, setSaved] = useState(false); const [selectedRoom, setSelectedRoom] = useState<string | null>(null); const [isLoginOpen, setIsLoginOpen] = useState(false);
  useEffect(() => { void fetch(`/api/properties/${encodeURIComponent(slug)}`, { cache: "no-store" }).then(async response => { const body = await response.json() as { property?: Property; error?: string }; if (!response.ok) throw new Error(body.error ?? "Unable to load property."); setProperty(body.property ?? null); }).catch(cause => setError(cause instanceof Error ? cause.message : "Unable to load property.")); }, [slug]);
  if (error) return <main className="mx-auto max-w-3xl p-12 text-center"><h1 className="text-2xl font-bold">Property unavailable</h1><p className="mt-3 text-[var(--hk-muted)]">This stay is not currently available to book.</p><Link href="/search" className="mt-6 inline-block rounded-lg bg-[var(--hk-navy-strong)] px-5 py-3 text-sm font-bold text-white">Browse stays</Link></main>;
  if (!property) return <main className="min-h-screen bg-[var(--hk-ivory)] p-12 text-center text-[var(--hk-muted)]">Loading property…</main>;
  const rating = property.ratingAverage || 4.8; const reviewCount = property.ratingCount || 128; const location = `${property.city}${property.state ? `, ${property.state}` : ""}`; const amenities = property.amenityCodes.length ? property.amenityCodes.map(item => item.replaceAll("_", " ").replace(/\b\w/g, char => char.toUpperCase())) : defaults;
  return <div className="min-h-screen bg-[var(--hk-ivory)] text-[var(--hk-ink)]">
    <SiteHeader onLoginClick={() => setIsLoginOpen(true)} />
    <main className="mx-auto max-w-[1280px] px-4 py-7 sm:px-6 lg:px-10"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap items-center gap-2 text-xs text-[var(--hk-muted)]"><Link href="/">Home</Link><ChevronRight className="h-3.5 w-3.5" /><Link href="/search">India</Link><ChevronRight className="h-3.5 w-3.5" /><Link href={`/search?destination=${encodeURIComponent(property.city)}`}>{property.city}</Link><ChevronRight className="h-3.5 w-3.5" /><span className="font-semibold text-[var(--hk-navy)]">{property.name}</span></nav>
      <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--hk-gold-strong)]">{property.propertyType}</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-[var(--hk-navy)] md:text-5xl">{property.name}</h1><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm"><span className="flex items-center gap-1 text-[var(--hk-muted)]"><MapPin className="h-4 w-4" />{location}</span><span className="flex items-center gap-1"><span className="tracking-[0.08em] text-[var(--hk-gold-strong)]">★★★★★</span><b>{rating.toFixed(1)}</b><span className="text-[var(--hk-muted)]">({reviewCount} reviews)</span></span><span className="flex items-center gap-1 font-semibold text-[var(--hk-success)]"><ShieldCheck className="h-4 w-4" />Verified Stay</span></div></div><div className="flex gap-3"><button className="flex flex-1 items-center justify-center gap-2 rounded-lg border border-[var(--hk-border-strong)] bg-white px-4 py-2.5 text-sm font-semibold text-[var(--hk-navy)] shadow-[var(--hk-shadow-soft)] md:flex-none"><Share2 className="h-4 w-4" />Share</button><button onClick={() => setSaved(value => !value)} className={`flex flex-1 items-center justify-center gap-2 rounded-lg border px-4 py-2.5 text-sm font-semibold shadow-[var(--hk-shadow-soft)] md:flex-none ${saved ? "border-[var(--hk-gold)] bg-[#fff8e8] text-[var(--hk-navy)]" : "border-[var(--hk-border-strong)] bg-white text-[var(--hk-navy)]"}`}><Heart className={`h-4 w-4 ${saved ? "fill-[var(--hk-gold-strong)]" : ""}`} />{saved ? "Saved" : "Save"}</button></div></div>
      <Gallery property={property} />
      <div className="mt-16 grid gap-10 lg:grid-cols-3"><div className="space-y-14 lg:col-span-2"><section><h2 className="text-2xl font-bold text-[var(--hk-navy)]">About this stay</h2><p className="mt-4 max-w-3xl text-base leading-8 text-[var(--hk-muted)]">Discover thoughtful hospitality at {property.name}. Located in the heart of {location}, this premium stay combines comfortable rooms, reliable service, and the practical details that make every business or leisure trip feel effortless.</p></section><section><h2 className="text-2xl font-bold text-[var(--hk-navy)]">Premium amenities</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 md:grid-cols-3">{amenities.slice(0, 6).map((amenity, index) => <Amenity key={amenity} label={amenity} index={index} />)}</div></section><section><div className="flex items-center justify-between"><h2 className="text-2xl font-bold text-[var(--hk-navy)]">Available rooms</h2><span className="text-sm text-[var(--hk-muted)]">Select a room to continue</span></div><div className="mt-6 space-y-5"><RoomCard title="Deluxe King Room" description="Comfortable city stay with a king-size bed and dedicated workspace." tags={["32 sq m", "City view", "Work desk"]} price={property.minimumPricePaise} currency={property.currency} image={property.coverImageUrl} selected={selectedRoom === "deluxe"} onSelect={() => setSelectedRoom("deluxe")} cancellation={property.freeCancellation} /><RoomCard title="Executive Suite" description="More room to unwind, with a separate living area and premium details." tags={["58 sq m", "Living area", "Premium view"]} price={property.minimumPricePaise === null ? null : Math.round(property.minimumPricePaise * 1.55)} currency={property.currency} image={property.coverImageUrl} selected={selectedRoom === "executive"} onSelect={() => setSelectedRoom("executive")} premium /></div></section><Reviews rating={rating} reviews={reviewCount} /></div><BookingCard property={property} rating={rating} selectedRoom={selectedRoom} /></div>
    </main><LoginModal isOpen={isLoginOpen} onClose={() => setIsLoginOpen(false)} />
  </div>;
}

function Gallery({ property }: { property: Property }) { const image = property.coverImageUrl; const blank = <div className="flex h-full items-center justify-center bg-[var(--hk-surface-muted)] text-[var(--hk-muted)]"><Hotel className="h-9 w-9" /></div>; return <section className="grid h-[390px] gap-4 md:h-[500px] md:grid-cols-4 md:grid-rows-2"><div className="relative overflow-hidden rounded-2xl bg-[var(--hk-surface-muted)] shadow-[var(--hk-shadow-soft)] md:col-span-3 md:row-span-2">{image ? <img src={image} alt={property.name} className="h-full w-full object-cover" /> : blank}</div><div className="hidden overflow-hidden rounded-2xl bg-[var(--hk-surface-muted)] shadow-[var(--hk-shadow-soft)] md:block">{image ? <img src={image} alt="Hotel interiors" className="h-full w-full object-cover brightness-90" /> : blank}</div><button className="relative hidden overflow-hidden rounded-2xl bg-[var(--hk-surface-muted)] shadow-[var(--hk-shadow-soft)] md:block">{image ? <img src={image} alt="Hotel amenities" className="h-full w-full object-cover brightness-75" /> : blank}<span className="absolute inset-0 flex items-center justify-center bg-[rgba(7,23,43,0.45)] text-sm font-bold text-white">View photos</span></button></section>; }
function Amenity({ label, index }: { label: string; index: number }) { const icons = [Wifi, BriefcaseBusiness, Utensils, Dumbbell, Coffee, Bath]; const Icon = icons[index % icons.length]; return <div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[var(--hk-surface-soft)] text-[var(--hk-navy)]"><Icon className="h-5 w-5" /></span><span className="text-sm font-semibold">{label}</span></div>; }
function RoomCard({ title, description, tags, price, currency, image, selected, onSelect, cancellation, premium = false }: { title: string; description: string; tags: string[]; price: number | null; currency: string; image: string | null; selected: boolean; onSelect: () => void; cancellation?: boolean; premium?: boolean }) { return <article className={`relative flex flex-col gap-5 rounded-2xl border bg-white p-5 shadow-[var(--hk-shadow-soft)] transition-shadow hover:shadow-[var(--hk-shadow-card)] md:flex-row ${premium ? "border-[var(--hk-gold)]" : "border-[var(--hk-border)]"}`}>{premium && <span className="absolute right-0 top-0 rounded-bl-lg bg-[var(--hk-gold)] px-3 py-1 text-[10px] font-bold text-[var(--hk-primary-dark)]">PREMIUM</span>}<div className="h-48 overflow-hidden rounded-lg bg-[var(--hk-surface-muted)] md:w-1/3 md:shrink-0">{image ? <img src={image} alt={title} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center"><BedDouble className="text-[var(--hk-muted)]" /></div>}</div><div className="flex flex-1 flex-col"><div><div className="flex justify-between gap-3"><h3 className="text-xl font-bold text-[var(--hk-navy)]">{title}</h3><span className="flex items-center gap-1 text-xs text-[var(--hk-muted)]"><Users className="h-4 w-4" />2 guests</span></div><p className="mt-2 text-sm leading-6 text-[var(--hk-muted)]">{description}</p><div className="mt-4 flex flex-wrap gap-2">{tags.map(tag => <span key={tag} className="rounded-md bg-[var(--hk-surface-soft)] px-2 py-1 text-xs font-medium text-[var(--hk-navy)]">{tag}</span>)}</div></div><div className="mt-5 flex items-end justify-between border-t border-[var(--hk-border)] pt-4"><div><p className="text-2xl font-bold text-[var(--hk-navy)]">{money(price, currency)} <span className="text-sm font-normal text-[var(--hk-muted)]">/ night</span></p>{cancellation ? <p className="mt-1 flex items-center gap-1 text-xs text-[var(--hk-success)]"><Check className="h-3.5 w-3.5" />Free cancellation</p> : <p className="mt-1 text-xs text-[var(--hk-muted)]">Non-refundable</p>}</div><button onClick={onSelect} className={`rounded-lg px-5 py-3 text-sm font-bold ${selected ? "bg-[var(--hk-gold)] text-[var(--hk-primary-dark)]" : "bg-[var(--hk-navy-strong)] text-white"}`}>{selected ? "Selected" : "Select"}</button></div></div></article>; }
function Reviews({ rating, reviews }: { rating: number; reviews: number }) { return <section><div className="flex items-center justify-between"><h2 className="text-2xl font-bold text-[var(--hk-navy)]">Guest reviews</h2><button className="text-sm font-semibold text-[var(--hk-navy)]">Read all {reviews} reviews</button></div><div className="mt-6 rounded-2xl border border-[var(--hk-border)] bg-white p-6 shadow-[var(--hk-shadow-soft)]"><div className="flex flex-col gap-6 md:flex-row md:items-center"><div className="border-[var(--hk-border)] text-center md:border-r md:pr-8"><p className="text-5xl font-bold text-[var(--hk-navy)]">{rating.toFixed(1)}</p><p className="mt-1 text-[var(--hk-gold-strong)]">★★★★★</p><p className="text-xs text-[var(--hk-muted)]">Exceptional</p></div><div className="grid flex-1 gap-4 sm:grid-cols-2">{["Cleanliness", "Service", "Location", "Value"].map((label, i) => <div key={label}><p className="flex justify-between text-xs font-semibold"><span>{label}</span><span>{(rating - i * 0.05).toFixed(1)}</span></p><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--hk-surface-soft)]"><div className="h-full rounded-full bg-[var(--hk-navy)]" style={{ width: `${Math.max(84, rating * 20 - i)}%` }} /></div></div>)}</div></div></div></section>; }
function BookingCard({ property, rating, selectedRoom }: { property: Property; rating: number; selectedRoom: string | null }) { const [guests, setGuests] = useState(2); const price = property.minimumPricePaise; return <aside className="relative"><div className="sticky top-24 rounded-2xl border border-[var(--hk-border)] bg-white p-6 shadow-[var(--hk-shadow-card)]"><div className="flex items-end justify-between border-b border-[var(--hk-border)] pb-5"><p><span className="text-3xl font-bold text-[var(--hk-navy)]">{money(price, property.currency)}</span><span className="text-sm text-[var(--hk-muted)]"> / night</span></p><span className="text-sm font-bold text-[var(--hk-navy)]">★ {rating.toFixed(1)}</span></div><div className="mt-5 grid grid-cols-2 gap-2"><Info label="Check-in" value="Select date" /><Info label="Check-out" value="Select date" /></div><button onClick={() => setGuests(value => value === 4 ? 1 : value + 1)} className="mt-2 flex w-full items-center justify-between rounded-lg border border-[var(--hk-border-strong)] p-3 text-left"><span><span className="block text-[10px] font-bold uppercase tracking-wide text-[var(--hk-muted)]">Guests</span><span className="text-sm font-semibold">1 room, {guests} guests</span></span><ChevronDown className="h-4 w-4" /></button><div className="mt-5 space-y-3 text-sm text-[var(--hk-muted)]"><p className="flex justify-between"><span>{money(price, property.currency)} × 2 nights</span><span>{price === null ? "—" : money(price * 2, property.currency)}</span></p><p className="flex justify-between"><span>Taxes & fees</span><span>Calculated at checkout</span></p><p className="flex justify-between border-t border-[var(--hk-border)] pt-3 text-lg font-bold text-[var(--hk-navy)]"><span>Total</span><span>{price === null ? "—" : money(price * 2, property.currency)}</span></p></div><Link href={`/search?destination=${encodeURIComponent(property.city)}`} className="mt-6 block rounded-xl bg-[var(--hk-navy-strong)] py-4 text-center text-base font-bold text-white">{selectedRoom ? "Reserve selected room" : "Select a room"}</Link><p className="mt-3 text-center text-xs text-[var(--hk-muted)]">You won’t be charged yet</p></div></aside>; }
function Info({ label, value }: { label: string; value: string }) { return <button className="rounded-lg border border-[var(--hk-border-strong)] p-3 text-left"><span className="block text-[10px] font-bold uppercase tracking-wide text-[var(--hk-muted)]">{label}</span><span className="mt-1 block text-sm font-semibold text-[var(--hk-navy)]">{value}</span></button>; }
