import { DeleteObjectCommand, GetObjectCommand, HeadObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";

type Config = { bucket: string; client: S3Client };
function endpoint() { const value = process.env.R2_ENDPOINT || (process.env.R2_ACCOUNT_ID ? `https://${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com` : ""); if (!value) throw new Error("R2_NOT_CONFIGURED"); return value.replace(/\/$/, ""); }
function client(id?: string, secret?: string) { if (!id || !secret) throw new Error("R2_NOT_CONFIGURED"); return new S3Client({ region: "auto", endpoint: endpoint(), forcePathStyle: true, credentials: { accessKeyId: id, secretAccessKey: secret } }); }
function privateBucket(): Config { const bucket = process.env.R2_PRIVATE_BUCKET_NAME || process.env.R2_BUCKET_NAME; if (!bucket) throw new Error("R2_NOT_CONFIGURED"); return { bucket, client: client(process.env.R2_PRIVATE_ACCESS_KEY_ID || process.env.R2_ACCESS_KEY_ID, process.env.R2_PRIVATE_SECRET_ACCESS_KEY || process.env.R2_SECRET_ACCESS_KEY) }; }
function publicBucket(): Config { const bucket = process.env.R2_PUBLIC_BUCKET_NAME; if (!bucket) throw new Error("PUBLIC_MEDIA_NOT_CONFIGURED"); return { bucket, client: client(process.env.R2_PUBLIC_WRITE_ACCESS_KEY_ID, process.env.R2_PUBLIC_WRITE_SECRET_ACCESS_KEY) }; }
function key(value: string) { if (!value || value.startsWith("/") || value.includes("\\") || value.includes("?") || value.includes("#") || value.split("/").some((p) => !p || p === "." || p === "..")) throw new Error("MEDIA_INVALID_OBJECT_KEY"); return value; }
export async function getPrivateObject(objectKey: string) { const c = privateBucket(); return c.client.send(new GetObjectCommand({ Bucket: c.bucket, Key: key(objectKey) })); }
export async function headPrivateObject(objectKey: string) { const c = privateBucket(); return c.client.send(new HeadObjectCommand({ Bucket: c.bucket, Key: key(objectKey) })); }
export async function deletePrivateObject(objectKey: string) { const c = privateBucket(); return c.client.send(new DeleteObjectCommand({ Bucket: c.bucket, Key: key(objectKey) })); }
export async function headPublicObject(objectKey: string) { const c = publicBucket(); return c.client.send(new HeadObjectCommand({ Bucket: c.bucket, Key: key(objectKey) })); }
export async function deletePublicObject(objectKey: string) { const c = publicBucket(); return c.client.send(new DeleteObjectCommand({ Bucket: c.bucket, Key: key(objectKey) })); }
export async function putPublicObject(objectKey: string, body: Uint8Array, metadata: Record<string, string>) { const c = publicBucket(); return c.client.send(new PutObjectCommand({ Bucket: c.bucket, Key: key(objectKey), Body: body, ContentLength: body.byteLength, ContentType: "image/webp", CacheControl: "public, max-age=31536000, immutable", Metadata: metadata })); }
function publicUrl(objectKey: string) { const base = process.env.PUBLIC_MEDIA_BASE_URL; if (!base) throw new Error("PUBLIC_MEDIA_NOT_CONFIGURED"); return new URL(key(objectKey).split("/").map(encodeURIComponent).join("/"), `${base.replace(/\/$/, "")}/`).toString(); }
export async function purgePublicUrls(keys: string[]) { if (!keys.length) return; const zone = process.env.CLOUDFLARE_ZONE_ID, token = process.env.CLOUDFLARE_CACHE_PURGE_TOKEN; if (!zone || !token) throw new Error("CACHE_PURGE_FAILED"); const response = await fetch(`https://api.cloudflare.com/client/v4/zones/${encodeURIComponent(zone)}/purge_cache`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ files: keys.map(publicUrl) }) }); if (!response.ok || !(await response.json() as { success?: boolean }).success) throw new Error("CACHE_PURGE_FAILED"); }
