import { FieldValue } from "firebase-admin/firestore";
import { z } from "zod";
import { getAuthenticatedUser } from "@/lib/auth/session";
import { adminDb } from "@/lib/firebase/admin";
import { requireAdmin } from "@/lib/admin/data";
import { enqueuePublicationInTransaction } from "@/lib/media-publication";

const schema = z.object({ decision: z.enum(["approve", "reject"]), reason: z.string().trim().min(2).max(1000).optional() }).strict();
export async function POST(request: Request, { params }: RouteContext<"/api/admin/properties/[propertyId]/assets/[assetType]/[assetId]/review">) {
  const user = await getAuthenticatedUser(); if (!user) return Response.json({ error: "Unauthenticated." }, { status: 401 });
  try { await requireAdmin(user.uid); const { propertyId, assetType, assetId } = await params; if (assetType !== "media" && assetType !== "documents") throw new Error("INVALID_ASSET_TYPE"); const input = schema.parse(await request.json()); if (input.decision === "reject" && !input.reason) throw new Error("REJECTION_REASON_REQUIRED"); const ref = adminDb.collection(assetType === "media" ? "mediaAssets" : "verificationDocuments").doc(assetId); let publicationStatus: string | null = null; await adminDb.runTransaction(async (tx) => { const asset = await tx.get(ref); const data = asset.data(); if (!asset.exists || !data || data.propertyId !== propertyId) throw new Error("ASSET_NOT_FOUND"); if (assetType === "media" && (data.kind !== "property_image" || typeof data.r2ObjectKey !== "string" || typeof data.checksum !== "string")) throw new Error("MEDIA_NOT_FOUND"); if (assetType === "media" && input.decision === "approve" && ["queued", "processing"].includes(data.publication?.status)) throw new Error("MEDIA_PUBLICATION_IN_PROGRESS"); tx.update(ref, { ...(assetType === "media" ? { moderationStatus: input.decision === "approve" ? "approved" : "rejected" } : { status: input.decision === "approve" ? "approved" : "rejected" }), reviewReason: input.decision === "reject" ? input.reason : null, reviewedAt: FieldValue.serverTimestamp(), reviewedBy: user.uid, updatedAt: FieldValue.serverTimestamp(), updatedBy: user.uid }); if (assetType === "media") { const operation = input.decision === "approve" ? "publish" : "unpublish"; enqueuePublicationInTransaction(tx, { operation, assetType: "property_image", assetId, sourceCollection: "mediaAssets", sourceObjectKey: data.r2ObjectKey, sourceChecksum: data.checksum }); publicationStatus = operation === "publish" ? "queued" : "unpublishing"; } }); return Response.json({ ok: true, publicationStatus }); }
  catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Unable to review asset." }, { status: 422 }); }
}
