import { FieldValue } from "firebase-admin/firestore";
import { z } from "zod";
import { getAuthenticatedUser } from "@/lib/auth/session";
import { adminDb } from "@/lib/firebase/admin";
import { propertyOwner } from "@/lib/partner/service";
import { copyPrivateObject, createR2ReadUrl, deletePrivateObject, getPrivateObject, verifyR2Object } from "@/lib/r2";
const schema = z.object({ uploadId: z.string().uuid() }).strict();

function isExpectedImage(bytes: Uint8Array, mimeType: string) {
  const jpeg = bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff;
  const png = bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47;
  const webp = bytes[0] === 0x52 && bytes[1] === 0x49 && bytes[2] === 0x46 && bytes[3] === 0x46 && bytes[8] === 0x57 && bytes[9] === 0x45 && bytes[10] === 0x42 && bytes[11] === 0x50;
  return (mimeType === "image/jpeg" && jpeg) || (mimeType === "image/png" && png) || (mimeType === "image/webp" && webp);
}

export async function POST(request: Request, { params }: RouteContext<"/api/partner/properties/[propertyId]/media/finalize">) { const user = await getAuthenticatedUser(); if (!user) return Response.json({ error: "Unauthenticated." }, { status: 401 }); try { const { propertyId } = await params; const property = await propertyOwner(user.uid, propertyId); const { uploadId } = schema.parse(await request.json()); const upload = await adminDb.collection("pendingUploads").doc(uploadId).get(); const data = upload.data(); if (!data || data.ownerId !== user.uid || data.propertyId !== propertyId || data.kind !== "property_image" || data.expiresAt < Date.now()) throw new Error("UPLOAD_EXPIRED"); await verifyR2Object(data.objectKey, data.sizeBytes, data.checksum); if (!isExpectedImage(await getPrivateObject(data.objectKey), data.mimeType)) throw new Error("INVALID_IMAGE_CONTENT"); const asset = adminDb.collection("mediaAssets").doc(); const originalKey = `originals/properties/${propertyId}/${asset.id}`; await copyPrivateObject(data.objectKey, originalKey); await verifyR2Object(originalKey, data.sizeBytes, data.checksum); await asset.set({ propertyId, ownerId: user.uid, kind: "property_image", category: data.category, fileName: data.fileName, mimeType: data.mimeType, sizeBytes: data.sizeBytes, checksum: data.checksum, r2ObjectKey: originalKey, isPrivate: true, moderationStatus: "pending", status: "pending", publication: { status: "private", sourceChecksum: data.checksum, variants: {}, attempts: 0, lastErrorCode: null, queuedAt: null, publishedAt: null, updatedAt: FieldValue.serverTimestamp() }, createdAt: FieldValue.serverTimestamp(), createdBy: user.uid, updatedAt: FieldValue.serverTimestamp(), updatedBy: user.uid }); const current = await property.get(); const hadCover = Boolean(current.data()?.coverMediaId); await property.update({ mediaIds: FieldValue.arrayUnion(asset.id), ...(hadCover ? {} : { coverMediaId: asset.id }), updatedAt: FieldValue.serverTimestamp(), updatedBy: user.uid }); await upload.ref.delete(); await deletePrivateObject(data.objectKey).catch(() => {}); let imageUrl: string | null = null; try { imageUrl = (await createR2ReadUrl(originalKey)).url; } catch { imageUrl = null; } return Response.json({ mediaId: asset.id, media: { id: asset.id, kind: "property_image", category: data.category ?? null, fileName: data.fileName ?? null, altText: "", moderationStatus: "pending", publicationStatus: "private", isCover: !hadCover, imageUrl }, coverMediaId: hadCover ? current.data()?.coverMediaId : asset.id }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Unable to finalize upload." }, { status: 422 }); } }
