"use client";

import { AlertTriangle, CheckCircle2, Copy, Fingerprint, Loader2, RefreshCw, ShieldAlert } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type LabRecord = { id: string; environment: "sandbox" | "production"; status: string; cashfreeReference: string | null; aadhaarLastFour: string; consentAt: string | null; createdAt: string | null; otpExpiresAt: string | null; resendCount: number; errorCode: string | null; timingMs: number | null };
type Readiness = { sandboxReady: boolean; productionEnabled: boolean; retentionDays: number; liveConfirmation: string };
type Result = { record: LabRecord; provider: { status: unknown; message: unknown; reference: unknown }; identity: globalThis.Record<string, unknown> };

const noStore = { "Content-Type": "application/json", "Cache-Control": "no-store" };
export function AadhaarLabPage() {
  const [records, setRecords] = useState<LabRecord[]>([]), [readiness, setReadiness] = useState<Readiness | null>(null), [aadhaar, setAadhaar] = useState(""), [otp, setOtp] = useState(""), [consent, setConsent] = useState(false), [environment, setEnvironment] = useState<"sandbox" | "production">("sandbox"), [confirmation, setConfirmation] = useState(""), [active, setActive] = useState<Result | null>(null), [payload, setPayload] = useState<unknown>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/admin/aadhaar-lab", { cache: "no-store" }); const data = await response.json(); if (response.ok) { setRecords(data.records); setReadiness(data.readiness); } else setError(data.error ?? "Unable to load Aadhaar Lab."); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function requestOtp() { setLoading(true); setError(null); setPayload(null); try { const response = await fetch("/api/admin/aadhaar-lab", { method: "POST", headers: noStore, body: JSON.stringify({ aadhaar, consentAttested: consent, environment, liveConfirmation: confirmation }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "OTP request failed."); setActive(data); setOtp(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "OTP request failed."); } finally { setLoading(false); } }
  async function verifyOtp() { if (!active) return; setLoading(true); setError(null); try { const response = await fetch(`/api/admin/aadhaar-lab/${active.record.id}/verify`, { method: "POST", headers: noStore, body: JSON.stringify({ otp }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "OTP verification failed."); setActive(data); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "OTP verification failed."); } finally { setLoading(false); } }
  async function resendOtp() { if (!active) return; setLoading(true); setError(null); try { const response = await fetch(`/api/admin/aadhaar-lab/${active.record.id}/resend`, { method: "POST", headers: noStore }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to resend OTP."); setActive(data); setOtp(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to resend OTP."); } finally { setLoading(false); } }
  async function showPayload(id: string) { setLoading(true); setError(null); try { const response = await fetch(`/api/admin/aadhaar-lab/${id}/payload`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to retrieve retained response."); setPayload(data.payload); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to retrieve retained response."); } finally { setLoading(false); } }
  function copy(value: string | null) { if (value) void navigator.clipboard.writeText(value); }
  const canLive = readiness?.productionEnabled ?? false;
  return <div className="space-y-6">
    <section className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-start sm:justify-between">
      <div><div className="flex items-center gap-2"><Fingerprint className="h-6 w-6 text-[#c6973e]" /><h1 className="text-xl font-bold text-slate-900">Aadhaar Verification Lab</h1></div><p className="mt-2 max-w-2xl text-sm text-slate-600">Restricted Cashfree Offline Aadhaar OTP testing. Use only with the holder’s informed consent. Aadhaar data is retained in encrypted private storage for {readiness?.retentionDays ?? 30} days; use an alternate ID when possible.</p></div>
      <div className={`rounded-lg px-3 py-2 text-xs font-semibold ${readiness?.sandboxReady ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-800"}`}>{readiness?.sandboxReady ? "Sandbox credentials ready" : "Sandbox setup incomplete"}</div>
    </section>
    {error && <div role="alert" className="flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800"><AlertTriangle className="h-4 w-4" />{error}</div>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(340px,.8fr)]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Start a test</h2><div className="mt-4 grid gap-4"><label className="text-sm font-medium text-slate-700">Environment<select className="mt-1.5 block w-full rounded-lg border border-slate-300 p-2.5" value={environment} onChange={e => setEnvironment(e.target.value as "sandbox" | "production")}><option value="sandbox">Sandbox (default)</option>{canLive && <option value="production">Production</option>}</select></label>{environment === "production" && <label className="text-sm font-medium text-red-800">Type: {readiness?.liveConfirmation}<input className="mt-1.5 block w-full rounded-lg border border-red-300 p-2.5" value={confirmation} onChange={e => setConfirmation(e.target.value)} /></label>}<label className="text-sm font-medium text-slate-700">Aadhaar number<input inputMode="numeric" autoComplete="off" className="mt-1.5 block w-full rounded-lg border border-slate-300 p-2.5" value={aadhaar} onChange={e => setAadhaar(e.target.value)} placeholder="12-digit Aadhaar" /></label><label className="flex gap-2 text-sm text-slate-700"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} />I attest that the Aadhaar holder has consented to this OTP verification and the stated retention.</label><button disabled={loading || !consent || !aadhaar} onClick={requestOtp} className="inline-flex w-fit items-center gap-2 rounded-lg bg-[#0a1f3c] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{loading && <Loader2 className="h-4 w-4 animate-spin" />}Generate OTP</button></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Active result</h2>{active ? <div className="mt-4 space-y-4 text-sm"><div className="rounded-xl bg-slate-50 p-3"><p className="font-semibold">{active.provider.status ? String(active.provider.status) : active.record.status}</p><p className="mt-1 text-slate-600">{active.provider.message ? String(active.provider.message) : "Provider response retained."}</p><p className="mt-2 font-mono text-xs text-slate-500">Reference: {active.record.cashfreeReference ?? "pending"}</p></div>{active.record.status === "otp_sent" && <div className="flex gap-2"><input inputMode="numeric" className="min-w-0 flex-1 rounded-lg border border-slate-300 p-2.5" placeholder="OTP" value={otp} onChange={e => setOtp(e.target.value)} /><button disabled={loading || !otp} onClick={verifyOtp} className="rounded-lg bg-[#c6973e] px-4 font-semibold text-[#261a00] disabled:opacity-50">Verify</button><button disabled={loading || active.record.resendCount >= 3} onClick={resendOtp} className="rounded-lg border border-slate-300 px-3 text-xs font-semibold disabled:opacity-50">Resend ({active.record.resendCount}/3)</button></div>}<div><p className="mb-2 flex items-center gap-1 font-semibold text-amber-800"><ShieldAlert className="h-4 w-4" />Sensitive result — view only when necessary</p><pre className="max-h-52 overflow-auto rounded-lg bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(active.identity, null, 2)}</pre></div></div> : <p className="mt-4 text-sm text-slate-500">Generate an OTP to see the active provider result here.</p>}</section>
    </div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Test history</h2><p className="text-xs text-slate-500">Metadata only. Full provider responses require an explicit open.</p></div><button onClick={() => void load()} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Refresh history"><RefreshCw className="h-4 w-4" /></button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-2">Time</th><th className="p-2">Environment</th><th className="p-2">Aadhaar</th><th className="p-2">Status</th><th className="p-2">Reference</th><th className="p-2">Actions</th></tr></thead><tbody>{records.map(record => <tr key={record.id} className="border-b border-slate-100"><td className="p-2 text-xs">{record.createdAt ? new Date(record.createdAt).toLocaleString() : "—"}</td><td className="p-2 capitalize">{record.environment}</td><td className="p-2">•••• {record.aadhaarLastFour}</td><td className="p-2"><span className="inline-flex items-center gap-1"><CheckCircle2 className="h-3.5 w-3.5 text-slate-400" />{record.status}</span></td><td className="p-2 font-mono text-xs">{record.cashfreeReference ?? "—"}</td><td className="p-2"><div className="flex gap-1"><button onClick={() => void showPayload(record.id)} className="rounded border px-2 py-1 text-xs">Open</button><button onClick={() => copy(record.cashfreeReference)} className="rounded border p-1" aria-label="Copy safe reference"><Copy className="h-3.5 w-3.5" /></button></div></td></tr>)}</tbody></table></div>{Boolean(payload) && <div className="mt-4"><p className="mb-2 flex items-center gap-1 text-sm font-semibold text-amber-800"><ShieldAlert className="h-4 w-4" />Complete retained provider payload — sensitive</p><pre className="max-h-96 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(payload, null, 2)}</pre></div>}</section>
  </div>;
}
