"use client";
import { Check, MessageSquare, RefreshCw, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
type Review = { id: string; propertyId: string; propertyName: string; reviewerName: string; rating: number; text: string; submittedAt: string | null; photos: Array<{ id: string; imageUrl: string; altText: string }> };
export function AdminReviewsPage() {
  const [reviews, setReviews] = useState<Review[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState<string | null>(null);
  const load = useCallback(async () => { setError(""); try { const res = await fetch("/api/admin/reviews", { cache: "no-store" }); const data = await res.json() as { reviews?: Review[]; error?: string }; if (!res.ok) throw new Error(data.error); setReviews(data.reviews ?? []); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load reviews."); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const moderate = async (id: string, decision: "approve" | "reject") => { setBusy(id); setError(""); try { const res = await fetch(`/api/admin/reviews/${encodeURIComponent(id)}/moderate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision, ...(decision === "reject" ? { reason: "Does not meet review guidelines" } : {}) }) }); const data = await res.json() as { error?: string }; if (!res.ok) throw new Error(data.error); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to moderate review."); } finally { setBusy(null); } };
  return <section className="space-y-6"><header className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#755a1a]">Guest feedback</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Review moderation</h1><p className="mt-2 text-sm text-slate-500">Approve reviews before they appear on property pages.</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold"><RefreshCw className="h-4 w-4" />Refresh</button></header>{error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{reviews.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500"><MessageSquare className="mx-auto mb-3 h-7 w-7" />No reviews are waiting for moderation.</div> : <div className="grid gap-4">{reviews.map(review => <article key={review.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold text-slate-900">{review.propertyName}</h2><p className="mt-1 text-sm text-slate-500">{review.reviewerName} · {"★".repeat(review.rating)} · {review.submittedAt ? new Date(review.submittedAt).toLocaleDateString("en-IN") : "Just now"}</p></div><div className="flex gap-2"><button disabled={busy === review.id} onClick={() => void moderate(review.id, "reject")} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700 disabled:opacity-50"><X className="h-4 w-4" />Reject</button><button disabled={busy === review.id} onClick={() => void moderate(review.id, "approve")} className="inline-flex items-center gap-1 rounded-lg bg-[#0a1f3c] px-3 py-2 text-sm font-bold text-white disabled:opacity-50"><Check className="h-4 w-4" />Approve</button></div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-700">{review.text}</p>{review.photos.length > 0 && <div className="mt-4 flex gap-2">{review.photos.map(photo => <img key={photo.id} src={photo.imageUrl} alt={photo.altText} className="h-20 w-20 rounded-lg object-cover" />)}</div>}</article>)}</div>}</section>;
}
